import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./containers/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ `${inter.className} overflow-x-hidden`}>
        <div className="px-20 py-10">

        <Header />
        {children}
        </div>
      </body>
    </html>
  );
}
